In [20]:
import torch

input2 = torch.load("input_embeds2.pt")
input1 = torch.load("input_embeds1.pt")
mask1 = torch.load("attention_mask1.pt")
mask2 = torch.load("attention_mask2.pt")
input3 = torch.load("input_embeds3.pt")
mask3 = torch.load("attention_mask3.pt")


In [4]:
input1.shape, input2.shape, mask1.shape, mask2.shape

(torch.Size([3, 121, 3584]),
 torch.Size([3, 123, 3584]),
 torch.Size([3, 121]),
 torch.Size([3, 123]))

In [10]:
input1[0].sum(axis=-1)

tensor([ 1.1104e+00,  1.1680e+00,  1.5781e+00,  1.0410e+00, -1.4697e+00,
         2.1387e+00,  1.2656e+00, -4.3311e-01, -2.3718e-01,  1.3623e+00,
         1.5781e+00,  4.8560e-01, -5.3662e-01, -5.9875e-02, -1.0872e+04,
         9.1309e-01, -5.3662e-01, -2.3621e-01,  1.0410e+00, -1.4697e+00,
         1.3086e+00,  1.3623e+00,  7.9980e-01,  5.3320e-01,  1.5781e+00,
         4.8560e-01,  4.4775e-01, -5.9875e-02,  1.4328e+04,  9.1309e-01,
         4.4775e-01, -2.3621e-01,  6.6455e-01,  8.0664e-01,  1.1475e+00,
        -3.4668e-01,  2.3108e-01,  6.8555e-01,  1.8176e-01,  1.8438e+00,
         8.5693e-01,  1.2656e+00,  2.1387e+00,  6.8652e-01, -4.4189e-01,
         1.8438e+00,  2.2461e+00,  1.8176e-01,  1.5781e+00,  4.8560e-01,
         1.9131e+00, -5.9875e-02,  2.1325e+02,  9.1309e-01,  1.9131e+00,
        -2.3621e-01,  1.0410e+00,  8.3496e-01,  2.7891e+00, -3.5962e-01,
         1.2656e+00,  1.3623e+00,  1.5781e+00,  4.8560e-01, -4.0479e-01,
        -1.2305e+00,  1.2529e+00,  1.8662e+00,  1.3

In [22]:
input2[2].sum(axis=-1) == input3[2].sum(axis=-1)[:123]

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True], device='cuda:0')

In [19]:
mask2[2]


tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False, False, False, False, False, False,
        False, False, False], device='cuda:0')